from crewai.tools import BaseTool
from typing import Type, Dict, Any, List
from pydantic import BaseModel, Field
from datetime import datetime
from typing import ClassVar
import json
import os


class ReportGenerationInput(BaseModel):
    """Input schema for ReportGenerator."""
    project_data: Dict = Field(..., description="聚合的项目分析数据")
    output_path: str = Field(default="output/report.md", description="报告输出路径")
    generate_qa: bool = Field(default=True, description="是否生成 QA 数据集")


class ReportGenerator(BaseTool):
    name: str = "Technical Report Generator"
    description: str = """将所有分析结果整合为结构化的 Markdown 技术报告。
    同时可以生成 QA 训练数据集用于模型微调。"""
    args_schema: Type[BaseModel] = ReportGenerationInput

    

    REPORT_TEMPLATE: ClassVar[str] = """# {project_name} - 技术分析报告

**生成时间:** {timestamp}  
**仓库地址:** [{repo_url}]({repo_url})  
**分析工具:** GitSeek v1.0  
**主要语言:** {main_language}

---

## 📊 执行摘要

{executive_summary}

**关键指标:**
- ⭐ Stars: {stars}
- 🍴 Forks: {forks}
- 👥 Contributors: {contributors}
- 📈 健康度评分: {health_score}/100

---

## 1️⃣ 项目概览

### 基本信息

| 属性 | 值 |
|------|-----|
| **项目名称** | {project_name} |
| **完整路径** | {full_name} |
| **主要语言** | {main_language} |
| **许可证** | {license} |
| **创建时间** | {created_at} |
| **最后更新** | {updated_at} |
| **仓库大小** | {size} KB |

### 项目描述

{description}

### 技术栈标签

{topics}

---

## 2️⃣ 架构分析

### 2.1 目录结构

{directory_structure}

### 2.2 核心模块识别

{core_modules}

### 2.3 配置文件分析

{config_files}

### 2.4 依赖关系

{dependencies}

### 2.5 架构评估

{architecture_assessment}

---

## 3️⃣ 代码质量评估

### 3.1 审查的关键文件

{reviewed_files}

### 3.2 代码质量指标

{code_quality_metrics}

### 3.3 识别的设计模式

{design_patterns}

### 3.4 代码复杂度分析

{code_complexity}

### 3.5 改进建议

{code_recommendations}

---

## 4️⃣ 社区动态分析

### 4.1 社区健康度

{community_health}

### 4.2 Issues 分析

{issue_analysis}

### 4.3 Pull Requests 分析

{pr_analysis}

### 4.4 主要贡献者

{contributors_analysis}

### 4.5 活跃度趋势

{activity_trends}

---

## 5️⃣ 综合评估与建议

### 5.1 项目优势

{project_strengths}

### 5.2 待改进领域

{improvement_areas}

### 5.3 战略建议

{strategic_recommendations}

### 5.4 技术债务评估

{technical_debt}

---

## 📈 总结

{conclusion}

---

**报告结束 | Report Generated by GitSeek**

---

## 附录：分析元数据

- **分析日期:** {timestamp}
- **分析工具版本:** GitSeek v1.0
- **数据来源:** GitHub API + 本地代码扫描
- **分析范围:** 完整仓库分析
"""

    def _run(self, project_data: Dict, output_path: str = "output/report.md", generate_qa: bool = True) -> Dict[str, Any]:
        """生成完整的技术分析报告"""
        try:
            # 确保输出目录存在
            os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
            
             # 🔥 新增：如果 project_data 为空，主动读取数据文件
            if not project_data or not project_data.get('metadata'):
                print("🔍 检测到空数据，开始从文件加载...")
                project_data = self._load_data_from_files()

            # 检查数据是否加载成功
            if not project_data.get('metadata'):
                error_msg = "❌ 无法获取项目数据，请确保前置任务已正确执行并生成数据文件"
                print(error_msg)
                return {"success": False, "error": error_msg}
            
            print(f"✅ 成功加载项目数据: {project_data['metadata'].get('name', 'Unknown')}")

            # 提取各部分数据
            metadata = project_data.get('metadata', {})
            architecture = project_data.get('architecture', {})
            code_review = project_data.get('code_review', {})
            community = project_data.get('community', {})
            
            # 生成报告内容
            report_content = self.REPORT_TEMPLATE.format(
                project_name=metadata.get('name', 'Unknown Project'),
                timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                repo_url=metadata.get('html_url', ''),
                main_language=metadata.get('language', 'N/A'),
                full_name=metadata.get('full_name', 'N/A'),
                stars=metadata.get('stars', 0),
                forks=metadata.get('forks', 0),
                contributors=community.get('total_contributors', 0),
                health_score=community.get('health_score', 0),
                executive_summary=self._generate_executive_summary(project_data),
                description=metadata.get('description', 'No description available.'),
                topics=self._format_topics(metadata.get('topics', [])),
                license=metadata.get('license', 'No license'),
                created_at=self._format_date(metadata.get('created_at')),
                updated_at=self._format_date(metadata.get('updated_at')),
                size=metadata.get('size', 0),
                directory_structure=self._format_directory_structure(architecture),
                core_modules=self._format_core_modules(architecture),
                config_files=self._format_config_files(architecture),
                dependencies=self._format_dependencies(architecture),
                architecture_assessment=self._assess_architecture(architecture),
                reviewed_files=self._format_reviewed_files(code_review),
                code_quality_metrics=self._format_quality_metrics(code_review),
                design_patterns=self._format_design_patterns(code_review),
                code_complexity=self._format_code_complexity(code_review),
                code_recommendations=self._format_code_recommendations(code_review),
                community_health=self._format_community_health(community),
                issue_analysis=self._format_issue_analysis(community),
                pr_analysis=self._format_pr_analysis(community),
                contributors_analysis=self._format_contributors(community),
                activity_trends=self._format_activity_trends(metadata, community),
                project_strengths=self._identify_strengths(project_data),
                improvement_areas=self._identify_improvements(project_data),
                strategic_recommendations=self._generate_strategic_recommendations(project_data),
                technical_debt=self._assess_technical_debt(code_review),
                conclusion=self._generate_conclusion(project_data)
            )
            
            # 写入报告文件
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(report_content)
            
            result = {
                "success": True,
                "report_path": output_path,
                "report_size": len(report_content),
                "timestamp": datetime.now().isoformat()
            }
            
            # 生成 QA 数据集
            if generate_qa:
                qa_path = output_path.replace('.md', '_qa_dataset.json')
                qa_dataset = self._generate_qa_dataset(project_data)
                
                with open(qa_path, 'w', encoding='utf-8') as f:
                    json.dump(qa_dataset, f, ensure_ascii=False, indent=2)
                
                result['qa_dataset_path'] = qa_path
                result['qa_pairs_count'] = len(qa_dataset)
            
            return result
            
        except Exception as e:
            return {"success": False, "error": f"报告生成失败: {str(e)}"}
    
        # 🔥 新增：文件读取方法
    def _load_data_from_files(self) -> Dict[str, Any]:
        """从数据文件加载项目数据"""
        data = {
            'metadata': {},
            'architecture': {},
            'code_review': {},
            'community': {}
        }
        
        try:
            # 读取侦察数据
            if os.path.exists('output/scout_data.json'):
                with open('output/scout_data.json', 'r', encoding='utf-8') as f:
                    scout_data = json.load(f)
                    data['metadata'] = scout_data.get('metadata', {})
                    print(f"✅ 加载元数据: {data['metadata'].get('name', 'Unknown')} - {data['metadata'].get('stars', 0)} stars")
            
            # 读取架构数据
            if os.path.exists('output/architect_data.json'):
                with open('output/architect_data.json', 'r', encoding='utf-8') as f:
                    arch_data = json.load(f)
                    data['architecture'] = arch_data
                    core_dirs = arch_data.get('core_directories', [])
                    print(f"✅ 加载架构数据: {len(core_dirs)} 个核心目录")
            
            # 读取代码审查数据
            if os.path.exists('output/code_review_data.json'):
                with open('output/code_review_data.json', 'r', encoding='utf-8') as f:
                    code_data = json.load(f)
                    data['code_review'] = code_data
                    avg_score = code_data.get('average_score', 'N/A')
                    print(f"✅ 加载代码数据: 平均分 {avg_score}")
            
            # 读取社区数据
            if os.path.exists('output/community_data.json'):
                with open('output/community_data.json', 'r', encoding='utf-8') as f:
                    community_data = json.load(f)
                    data['community'] = community_data
                    health_score = community_data.get('health_score', 'N/A')
                    print(f"✅ 加载社区数据: 健康度 {health_score}")
            
            # 检查数据完整性
            missing_sections = []
            if not data['metadata']:
                missing_sections.append('metadata')
            if not data['architecture']:
                missing_sections.append('architecture')
            if not data['code_review']:
                missing_sections.append('code_review') 
            if not data['community']:
                missing_sections.append('community')
                
            if missing_sections:
                print(f"⚠️ 缺失数据部分: {missing_sections}")
            else:
                print("✅ 所有数据文件加载完成")
                
        except Exception as e:
            print(f"❌ 读取数据文件失败: {e}")
            import traceback
            traceback.print_exc()
        
        return data
        
    # === 报告内容生成方法 ===
    
    def _generate_executive_summary(self, data: Dict) -> str:
        """生成执行摘要"""
        metadata = data.get('metadata', {})
        community = data.get('community', {})
        code_review = data.get('code_review', {})
        
        activity_level = community.get('activity_level', '未知')
        health_score = community.get('health_score', 0)
        
        return f"""本报告对 **{metadata.get('name', 'Unknown')}** 项目进行了全面的技术分析。

**分析覆盖范围:**
- ✅ 项目基本信息和元数据收集
- ✅ 文件架构和依赖关系分析
- ✅ 代码质量和设计模式评估
- ✅ 社区活跃度和贡献者分析

**核心发现:**
- 该项目目前处于 **{activity_level}** 状态
- 社区健康度评分为 **{health_score}/100**
- 代码质量评估为 **{code_review.get('overall_quality', 'N/A')}**
- 主要使用 **{metadata.get('language', 'N/A')}** 语言开发
"""

    def _format_topics(self, topics: List[str]) -> str:
        """格式化技术栈标签"""
        if not topics:
            return "暂无标签"
        return ", ".join([f"`{topic}`" for topic in topics])

    def _format_date(self, date_str: str) -> str:
        """格式化日期"""
        if not date_str:
            return "N/A"
        try:
            dt = datetime.fromisoformat(date_str.replace('Z', '+00:00'))
            return dt.strftime("%Y-%m-%d %H:%M")
        except:
            return date_str

    def _format_directory_structure(self, arch: Dict) -> str:
        """格式化目录结构"""
        structure = arch.get('structure', {})
        if not structure:
            return "目录结构数据未获取"
        
        # 🔥 修改：适配实际的数据结构
        root = structure.get('root', {})
        items = root.get('items', [])
        
        result = "```\n"
        for item in items[:8]:  # 显示前8个主要目录
            name = item.get('name', '')
            desc = item.get('description', '')
            if desc:
                result += f"{name}/     # {desc}\n"
            else:
                result += f"{name}/\n"
        result += "```\n\n"
        
        core_dirs = arch.get('core_directories', [])
        if core_dirs:
            result += f"**核心目录:** {', '.join(core_dirs)}"
        
        return result

    def _format_core_modules(self, arch: Dict) -> str:
        """格式化核心模块"""
        core_dirs = arch.get('core_directories', [])
        if not core_dirs:
            return "未识别到明确的核心模块"
        
        result = "识别到以下核心模块:\n\n"
        for idx, dir_name in enumerate(core_dirs, 1):
            result += f"{idx}. **{dir_name}** - 核心代码模块\n"
        
        return result

    def _format_config_files(self, arch: Dict) -> str:
        """格式化配置文件"""
        config_files = arch.get('config_files', [])
        if not config_files:
            return "未找到配置文件"
        
        result = "| 配置文件 | 类型 | 描述 |\n|---------|------|------|\n"
        for config in config_files[:10]:
            # 🔥 修改：适配实际的数据结构
            path = config.get('path', '')
            file_name = os.path.basename(path)
            file_type = config.get('type', self._identify_config_type(file_name))
            description = config.get('description', '')
            result += f"| `{file_name}` | {file_type} | {description} |\n"
        
        if len(config_files) > 10:
            result += f"\n*... 以及其他 {len(config_files) - 10} 个配置文件*\n"
        
        return result

    def _format_dependencies(self, arch: Dict) -> str:
        """格式化依赖关系"""
        deps = arch.get('dependencies', {})
        if not deps:
            return "依赖关系数据未获取"
        
        # 🔥 修改：显示实际的依赖数据
        result = "**主要依赖:**\n\n"
        
        python_deps = deps.get('python', {})
        if python_deps:
            result += "**Python 依赖:**\n"
            for category, packages in python_deps.items():
                result += f"- {category}: {len(packages)} 个包\n"
            result += "\n"
        
        js_deps = deps.get('javascript', {})
        if js_deps:
            result += "**JavaScript 依赖:**\n"
            for category, packages in js_deps.items():
                result += f"- {category}: {len(packages)} 个包\n"
        
        return result

    def _format_reviewed_files(self, code_review: Dict) -> str:
        """格式化审查的文件列表"""
        files = code_review.get('reviewed_files', [])
        if not files:
            return "暂无代码审查数据"
        
        result = "| 文件 | 语言 | 代码行数 | 质量评分 |\n"
        result += "|------|------|----------|----------|\n"
        
        for file_info in files[:8]:  # 显示前8个文件
            file_path = file_info.get('file_path', '')
            file_name = os.path.basename(file_path)
            reason = file_info.get('selection_reason', '')[:50] + "..." if len(file_info.get('selection_reason', '')) > 50 else file_info.get('selection_reason', '')
            analysis = file_info.get('analysis', {})
            score = analysis.get('overall_score', 'N/A')
            
            result += f"| `{file_name}` | {reason} | {score}/100 |\n"
        
        return result

    def _format_quality_metrics(self, code_review: Dict) -> str:
        """格式化代码质量指标"""
        return f"""**总体评估:**
- 平均质量评分: {code_review.get('average_score', 'N/A')}/100
- 代码可读性: {code_review.get('readability', 'N/A')}
- 注释覆盖率: {code_review.get('comment_coverage', 'N/A')}%
"""

    def _format_design_patterns(self, code_review: Dict) -> str:
        """格式化设计模式"""
        patterns_data = code_review.get('design_patterns', [])
        if not patterns_data:
            return "未检测到明显的设计模式"
        
        # 🔥 修改：适配实际的数据结构
        if isinstance(patterns_data, list) and patterns_data and isinstance(patterns_data[0], dict):
            # 新的数据结构：列表中的字典
            result = "识别到以下设计模式:\n\n"
            for pattern_info in patterns_data:
                pattern = pattern_info.get('pattern', '')
                usage = pattern_info.get('usage', '')
                files = pattern_info.get('files', [])
                result += f"- **{pattern}**: {usage} (文件: {', '.join(files[:3])})\n"
        else:
            # 旧的数据结构：简单的字符串列表
            result = "识别到以下设计模式:\n\n"
            for pattern in set(patterns_data):
                result += f"- {pattern}\n"
        
        return result

    def _format_code_complexity(self, code_review: Dict) -> str:
        """格式化代码复杂度"""
        return f"""**复杂度指标:**
- 平均圈复杂度: {code_review.get('avg_complexity', 'N/A')}
- 可维护性指数: {code_review.get('maintainability_index', 'N/A')}/100
"""

    def _format_code_recommendations(self, code_review: Dict) -> str:
        """格式化代码改进建议"""
        recommendations = code_review.get('recommendations', [])
        if not recommendations:
            return "代码质量良好，暂无重大改进建议"
        
        result = ""
        for idx, rec in enumerate(recommendations, 1):
            result += f"{idx}. {rec}\n"
        
        return result

    def _format_community_health(self, community: Dict) -> str:
        """格式化社区健康度"""
        return f"""**健康度评分:** {community.get('health_score', 0)}/100

**关键指标:**
- 活跃度等级: {community.get('activity_level', 'N/A')}
- 社区参与度: {community.get('community_engagement', 'N/A')}
- Issue 关闭率: {community.get('issue_closure_rate', 0)}%
- PR 合并率: {community.get('pr_merge_rate', 0)}%
"""

    def _format_issue_analysis(self, community: Dict) -> str:
        """格式化 Issue 分析"""
        issues = community.get('issues', {})
        return f"""**统计数据:**
- Open Issues: {issues.get('open_issues', 0)}
- Closed Issues: {issues.get('closed_issues', 0)}
- 关闭率: {issues.get('closure_rate', 0)}%

**热点问题:**
{self._format_hot_issues(issues.get('hot_issues', []))}
"""

    def _format_hot_issues(self, hot_issues: List[Dict]) -> str:
        """格式化热点问题"""
        if not hot_issues:
            return "暂无热点问题"
        
        result = ""
        for issue in hot_issues[:5]:
            result += f"- #{issue.get('number')}: {issue.get('title')} ({issue.get('comments')} 评论)\n"
        
        return result

    def _format_pr_analysis(self, community: Dict) -> str:
        """格式化 PR 分析"""
        prs = community.get('prs', {})
        return f"""**统计数据:**
- Merged PRs: {prs.get('merged_prs', 0)}
- Open PRs: {prs.get('open_prs', 0)}
- 合并率: {prs.get('merge_rate', 0)}%

**代码变更:**
- 总新增行数: {prs.get('total_additions', 0)}
- 总删除行数: {prs.get('total_deletions', 0)}
"""

    def _format_contributors(self, community: Dict) -> str:
        """格式化贡献者信息"""
        contributors = community.get('top_contributors', [])
        if not contributors:
            return "暂无贡献者数据"
        
        result = "| 排名 | 贡献者 | 贡献次数 |\n|------|--------|----------|\n"
        for contrib in contributors[:10]:
            result += f"| {contrib.get('rank', 'N/A')} | {contrib.get('login', 'N/A')} | {contrib.get('contributions', 0)} |\n"
        
        return result

    def _format_activity_trends(self, metadata: Dict, community: Dict) -> str:
        """格式化活跃度趋势"""
        return f"""基于最近更新时间和社区活动:
- 最后更新: {self._format_date(metadata.get('updated_at'))}
- 活跃度: {community.get('activity_level', '未知')}
"""

    def _identify_strengths(self, data: Dict) -> str:
        """识别项目优势"""
        strengths = []
        
        metadata = data.get('metadata', {})
        community = data.get('community', {})
        
        if metadata.get('stars', 0) > 100:
            strengths.append("✅ 受到社区广泛关注 (Stars > 100)")
        
        if community.get('health_score', 0) > 70:
            strengths.append("✅ 社区健康度高")
        
        if community.get('activity_level', '').startswith('活跃'):
            strengths.append("✅ 项目保持活跃开发")
        
        return "\n".join(strengths) if strengths else "待进一步分析"

    def _identify_improvements(self, data: Dict) -> str:
        """识别待改进领域"""
        improvements = []
        
        community = data.get('community', {})
        code_review = data.get('code_review', {})
        
        if community.get('issue_closure_rate', 0) < 50:
            improvements.append("⚠️ Issue 关闭率较低，需要改进问题响应")
        
        if community.get('pr_merge_rate', 0) < 50:
            improvements.append("⚠️ PR 合并率较低，建议优化审查流程")
        
        if code_review.get('average_score', 100) < 70:
            improvements.append("⚠️ 代码质量有待提升")
        
        return "\n".join(improvements) if improvements else "无明显待改进项"

    def _generate_strategic_recommendations(self, data: Dict) -> str:
        """生成战略建议"""
        return """**建议优先级:**

1. **短期 (1-3个月):**
   - 改进文档质量
   - 增加单元测试覆盖率
   - 响应社区 Issues

2. **中期 (3-6个月):**
   - 优化项目架构
   - 重构高复杂度代码
   - 提升代码质量

3. **长期 (6-12个月):**
   - 扩大社区影响力
   - 建立完善的贡献者指南
   - 持续优化性能
"""

    def _assess_technical_debt(self, code_review: Dict) -> str:
        """评估技术债务"""
        return f"""**技术债务评估:**
- 代码复杂度: {code_review.get('avg_complexity', 'N/A')}
- 待改进问题数: {code_review.get('total_issues', 0)}
- 建议投入时间: 根据问题优先级逐步改进
"""

    def _generate_conclusion(self, data: Dict) -> str:
        """生成总结"""
        metadata = data.get('metadata', {})
        return f"""**{metadata.get('name', 'Unknown')}** 项目的技术分析已完成。

整体而言，该项目展现出良好的发展潜力。建议项目维护者根据本报告的具体建议，
持续改进代码质量、优化架构设计、增强社区参与度。

本报告可作为项目改进的参考依据和技术决策的支持材料。
"""

    # === QA 数据集生成 ===
    
    def _generate_qa_dataset(self, project_data: Dict) -> List[Dict]:
        """生成 QA 训练数据集"""
        qa_pairs = []
        
        metadata = project_data.get('metadata', {})
        architecture = project_data.get('architecture', {})
        code_review = project_data.get('code_review', {})
        community = project_data.get('community', {})
        
        # 1. 项目基本信息相关问答
        qa_pairs.extend([
            {
                "question": f"{metadata.get('name')} 项目的主要编程语言是什么?",
                "answer": f"该项目主要使用 {metadata.get('language', 'N/A')} 语言开发。",
                "category": "基本信息"
            },
            {
                "question": f"{metadata.get('name')} 项目有多少 Stars?",
                "answer": f"该项目目前有 {metadata.get('stars', 0)} 个 Stars。",
                "category": "基本信息"
            },
            {
                "question": f"{metadata.get('name')} 项目的描述是什么?",
                "answer": metadata.get('description', '暂无描述'),
                "category": "基本信息"
            }
        ])
        
        # 2. 架构相关问答
        core_dirs = architecture.get('core_directories', [])
        if core_dirs:
            qa_pairs.append({
                "question": f"{metadata.get('name')} 项目的核心目录有哪些?",
                "answer": f"该项目的核心目录包括: {', '.join(core_dirs)}",
                "category": "架构"
            })
        
        # 3. 代码质量相关问答
        if code_review.get('average_score'):
            qa_pairs.append({
                "question": f"{metadata.get('name')} 项目的代码质量如何?",
                "answer": f"该项目的平均代码质量评分为 {code_review.get('average_score')}/100",
                "category": "代码质量"
            })
        
        # 4. 社区相关问答
        qa_pairs.extend([
            {
                "question": f"{metadata.get('name')} 项目的社区活跃度如何?",
                "answer": f"该项目的活跃度等级为: {community.get('activity_level', '未知')}",
                "category": "社区"
            },
            {
                "question": f"{metadata.get('name')} 项目有多少贡献者?",
                "answer": f"该项目目前有 {community.get('total_contributors', 0)} 位贡献者。",
                "category": "社区"
            }
        ])
        
        # 5. 问题和改进相关问答
        improvements = self._identify_improvements(project_data)
        if improvements and improvements != "无明显待改进项":
            qa_pairs.append({
                "question": f"{metadata.get('name')} 项目有哪些需要改进的地方?",
                "answer": improvements,
                "category": "改进建议"
            })
        
        return qa_pairs
